# module name not a source file for multi-file builds
obj-m := ess_iio_moc.o
# one of these files contains the module MACRO credentials
ess_iio_moc-objs := iio_canonical_moc.o

# all:
# 	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

# clean:
# 	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean
